### ISSUE TITLE
gremlin-haskell is inactive

### ISSUE THREAD

**Issue by debug-ito** [mohataher/awesome-tinkerpop#10]
Related to #4 

`gremlin-haskell` is inactive. There are some issues that prevent it from connecting to the latest TinkerPop Gremlin Server. Those issues were reported in 2016 and 2017, but haven't been handled yet.

**Comment by mohataher** [comment]
Sorry it has been two years since you opened up this ticket. I have just removed gremlin-haskell from the list. Have you encountered any other libraries that should be updated? If so, please feel free to open up another ticket.

**Comment by debug-ito** [comment]
Thanks! I'm not sure about other libraries, though.
