### ISSUE TITLE
Conflicting licenses within the repo

### ISSUE THREAD

**Issue by mbrukman** [mohataher/awesome-tinkerpop#2]
The [`README.md`](https://github.com/mohataher/awesome-tinkerpop/blob/0835d61d071cb27e2b737633bcc54c01cd2b59be/README.md#license) says:

> ## <A NAME="license"></A>License
> [![CC0](https://licensebuttons.net/p/zero/1.0/88x31.png)](http://creativecommons.org/publicdomain/zero/1.0/)
> 
> To the extent possible under law, [@mohataher](https://github.com/mohataher) has waived all copyright and related or neighboring rights to this work.

However, [`LICENSE`](https://github.com/mohataher/awesome-tinkerpop/blob/f974bc514f0f3943cbbfea52ac66eab1513adc0b/LICENSE) contains the full text of the Apache 2.0 license, thus there's a conflict between these two statements in this repo.

Apache 2.0 is a well-recognized license (in contrast to public domain / CC0, which are not [universally](https://opensource.org/faq#public-domain) [recognized](https://opensource.org/faq#cc-zero)), so I would recommend removing the mention of the CC0 / public domain and leaving the Apache 2.0 license intact.

**Comment by mohataher** [comment]
Good spot. Thanks for letting me know. I will try to solve this issue as soon as I have time. Your contribution is welcome :) .
