### ISSUE TITLE
Ferma supports Tinkerpop3 and Tinkerpop2

### ISSUE THREAD

**Issue by freemo** [mohataher/awesome-tinkerpop#3]
Ferma has support for both Tinkerpop3 and Tinkerpop2, the list should be updated to reflect this.

**Comment by mohataher** [comment]
Good to hear from you again Jeffery. Added it to TP3 list.

**Comment by freemo** [comment]
@mohataher you as well :) Hope all is well in your world. Thanks for the update on the list.
