### ISSUE TITLE
We need to look for GUIs

### ISSUE THREAD

**Issue by The-Don-Himself** [mohataher/awesome-tinkerpop#5]
This list is great but lacks a list of Graphical User Interfaces. Of course there is Gephi, but I find it hard to find anything a bit more modern and lightweight.

I know the folks at Compose created their own, https://www.compose.com/articles/announcing-the-data-browser-for-janusgraph/ and they have had internal discussion on whether to open-source it.

Anyway, created this issue for us to find some GUIs to add to this awesome list.

**Comment by mohataher** [comment]
Hi Don, good shout. I'll be more than happy to add it to the list unless you prefer to be a contributor. You can add it at the bottom of the sub categories. Please let me know if you want to do it.

Regarding other tools, I scout for any new 'awesome' projects that deserve to be added here every other month. I may do that in few days and will look specifically for visualisation tools. Please let me know if you spotted any thing.

**Comment by The-Don-Himself** [comment]
Hi @mohataher , it's great you agree that GUIs should be added to awesome list, the challenge is getting some. I am definitely up to being a contributor. We can start with Gephi which seems to be the most complete, there are others but they come without connectors to a graph database so developers would have to write one up.

I like this one: https://github.com/strathausen/dracula
Sigma.js is also great: https://github.com/jacomyal/sigma.js

I think gun deserves an honourable mention but I am not quite sure where
gun.js: https://github.com/amark/gun

Thoughts?

**Comment by mohataher** [comment]
I had a look at the three and I'm under the impression they don't support Tinkerpop APIs. Am I wrong?

**Comment by The-Don-Himself** [comment]
You and right,they don't natively support Tinkerpop APIs, but then again I haven't really come across any GUI that does, other than Compose's JanusGraph Data Browser. Gephi, requires a plugin but when used it seems native enough.

The libraries I mentioned can support Tinkerpop but you'd have to do all the bindings and querying manually. I believe dracula could be behind Compose's JanusGraph database browser, because of the striking similarities (I don't have in-depth knowledge though). While I also believe sigma.js is behind a specific GUI by Dylan Millikin https://github.com/PommeVerte/gc-cytoscape-plugin. So they all support Tinkerpop but developers must write the glue to stick it. There maybe a GUI by DataStax since they acquired Titan and converted it into DataStax Enterprise Graph, but I think it will be tied to DataStax studio, haven't tried it yet so can't comment. Sadly, these are the few GUI options I've ever found.

Gun.js was just a very awesome library I found that I though would be great to share, haven't seen a robust Tinkerpop integration with it yet.

**Comment by The-Don-Himself** [comment]
On further investigation, the 2nd library uses cytoscape.js https://github.com/cytoscape/cytoscape.js

**Comment by mohataher** [comment]
The only one that supports Gremlin is @PommeVerte one. Unfortunately the last commit was 2 years ago. That is not an awesome library any more. Have you come across any other libraries?
