### ISSUE TITLE
Add 'Graph Databases, Gremlin and TinkerPop - A Tutorial'

### ISSUE THREAD

**Issue by The-Don-Himself** [mohataher/awesome-tinkerpop#6]
I propose to add https://github.com/krlawrence/graph to Tutorials and Resources

**Comment by mohataher** [comment]
Nice suggestion Don. Just added it. 

Feel free to keep opening issues. You can also send a pull request next time. It's easy too; have a look https://github.com/mohataher/awesome-tinkerpop/blob/master/contributing.md . That way you would count as a contributor to this repo.
